# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf1cbcd3634fc11487e63aac64ad12afcbdd2dcab33952630b2c956b60e90c916dc5c8fa25ce46bc1f65879815fb854843b243fc8597fca7399198fc719a1cc7

test:
  secret_key_base: f81df634bb98967858c334348e90ee55542e5157ca0b97ff45761f0ae7d863378215f83c77b17eec95637c0e6eb46688e579a31b8db3764eb0f899735b072fb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
